### ISSUE TITLE
iOS crashes with no trace when .setUserId(null) is called.

### ISSUE THREAD

**Issue by saarikivit** [amplitude/Amplitude-Flutter#10]
Hi! Awesome library btw. Helps my startup stay legal, lol.

*Please note, that this code crashes only on iOS, not Android.*

This is the relevant code:

```
  AmplitudeService({
    @required this.apiKey,
    @required this.userLocale,
    @required this.resolvedLocale,
    @required this.optOut,
  }) {
    _client = Amplitude.getInstance(instanceName: 'turnip');
    _client.init(apiKey);
    _client.enableCoppaControl();
    _client.trackingSessionEvents(true);
    _client.setOptOut(optOut);
  }

  void setToken(Token token) {
    if (token == null) {
       _client.setUserId(
        null,
        startNewSession: true,
      );
    } else {
      // set user id
      final userId = token?.userId;
      _client.setUserId(userId);

      final userRole = token?.userRole;
      final subsCategory = token?.subscriptionCategory;

      _client.setUserProperties({
        'userRole': userRole,
        'subscriptionCategory': subsCategory,
      });
    }
  }
```

Here in **void setToken**, *if token == null*, _client.setUserId crashes the whole app and leaves no trace. The same thing happens even if I do not specify startNewSession: true.

If I comment out the _client.setUserId(null). Everything works as expected.

To be honest this is not the end of the world and does not dilute the data too much. But it would be handy to be able to "sign out" a user and be able to there and then start a new session.

Am I doing it wrong perhaps?

**Comment by haoliu-amp** [comment]
@saarikivit Hello, we will take a look into this. Thanks for reporting.

**Comment by saarikivit** [comment]
Thanks for looking in to it!

Question:
.init and the .enablecoppa .sessionevents .setoptout methods return a Future.

Is there a benefit to await them?

**Comment by haoliu-amp** [comment]
@saarikivit No a big problem, you can choose to `await` if you wanna guarantee the sequential execution. 

Overall, I would say the different would be minimal.

**Comment by haoliu-amp** [comment]
It should be fixed. Thanks!
