### ISSUE TITLE
Only few of the events get synced to the amplitude dashboard

### ISSUE THREAD

**Issue by HeyitSaif** [amplitude/Amplitude-Flutter#100]
we have the app which has lots of event.  only the events on the home page are getting reported accurately. if the user starts navigating to other screens the event start getting missed even though it is being called accurately. there is no exception related to any thing in the code. plus we have tried to run it in debug mode set to catch all exceptions and there is none.
## Expected Behavior
All of the event should be reported perfectly fine.

## Current Behavior
some events don't get reported. they don't follow any specific pattern. sometime it  keeps on reporting way past few screen sometimes it stops no concentrate way to reproduce that..
## Possible Solution
is there a way to turn the dubgging on for the sdk?? to check what's exactly going on there??

## Steps to Reproduce
just start the app
navigate back and forth few screens then event will eventually be stopped and you will not see any thing on dashboard.
sometime it keeps on going and only certain events doesn't get sent.
the specific even we are consistently having issue with is "join call" event.

## Environment
- SDK Version: ^3.8.1
- Flutter Version: 2.10.2
- Device: Poco X3, oneplus, emulator almost all of the devices 
- Device OS and Version: android 11, android 12.

**Comment by yuhao900914** [comment]
Hi @HeyitSaif, sorry for the late reply. 
Does this issue happen on both Android and iOS sites? 
Is it possible to provide me with an example app in order to reproduce it?

**Comment by yuhao900914** [comment]
I saw you said the `join call` event consistently has an issue. Some more detailed information about where this event gets called and how the life cycle works will also be helpful. Thanks.

**Comment by HeyitSaif** [comment]
ah found the issue. the issue was that we were using jitsi_meet flutter package as well which is also using the amplitude as a dependency. so when ever we call that specific widget the events were stopped being reported.
the solution was to name amplitude instance so they don't get overlap.
i suggest making the instance name required in the sdk so such cases never exist in the first place. 

`final analytics = Amplitude.getInstance(instanceName: 'test');`
