### ISSUE TITLE
amplitude_flutter/amplitude_flutter-Swift.h' file not found

### ISSUE THREAD

**Issue by vitulgoyani** [amplitude/Amplitude-Flutter#103]
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/wk/smm6mfxn6dd6rcv8vjtj49qr0000gn/T/flutter_tools.K1r3vy/flutter_ios_build_temp_diruJpgfh/temporary_xcresult_bundle

    /Users/vitul/Documents/Software/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.1/ios/Classes/AmplitudeFlutterPlugin.m:2:9: fatal error: 'amplitude_flutter/amplitude_flutter-Swift.h' file not found
    #import <amplitude_flutter/amplitude_flutter-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

    Result bundle written to path:
    	/var/folders/wk/smm6mfxn6dd6rcv8vjtj49qr0000gn/T/flutter_tools.K1r3vy/flutter_ios_build_temp_diruJpgfh/temporary_xcresult_bundle

**Comment by yuhao900914** [comment]
Hi @vitulgoyani , 
Can you provide more details about how we can reproduce this issue? Did you run build in Xcode or through the command line? 
Did you run pod install in the iOS folder? 
Also, what's your flutter version and Xcode version?

**Comment by petri-lipponen-movesense** [comment]
I'm having a same issue and it's preventing me creating ios version of the app.

XCode 13.2.1 (13C100), pod install run manually as well as part of "flutter build ios" (flutter run ends up with same error. The only thing I did was to change the team and signing in xcode project target. 

Android builds & runs fine.

Pubspec.lock tells that amplitude_flutter is version 3.9.0

**Comment by bgoncharuck** [comment]
Having the same issue with iOS

**Comment by yuhao900914** [comment]
Hi there, can you run `flutter doctor -v` and share the result back?

**Comment by bgoncharuck** [comment]
Here you go https://pastebin.com/M1iFShZt
iOS device:
`• Ipnone (mobile) • aab1fc5346f6aef8717343c927ab92401c27ae79 • ios            • iOS 15.5 19F77`

**Comment by yuhao900914** [comment]
Thanks. I will take a look today and get back to you.

**Comment by bgoncharuck** [comment]
Thank you for such a quick colaboration, @yuhao900914. Looking forward to solve this issue.
My main presumption is that the new XCode version needed for a new flutter SDK messes something up. Because every version of plugin has this issue. And Android version works just fine.

**Comment by yuhao900914** [comment]
@bgoncharuck,
I created a new app and integrate with amplitude flutter 3.8.1 successfully. And I'm using the XCode 13.4.1 
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 3.0.1 at /Users/hao.yu/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2
```
Did you run `pod install` under the `ios` folder? 
Can you also share your Podfile? 
Do `use_frameworks!` and `use_modular_headers!`  exist in your Runner target? 

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by bgoncharuck** [comment]
@yuhao900914 
Sure I did, and everything were installed by pod install.
And yes, I don't have use_frameworks! in my Podfile. It's old. Thanks a lot, I am trying it out!

**Comment by bgoncharuck** [comment]
@yuhao900914 adding the use_frameworks! to the Podfile mess up with other package https://github.com/googleads/googleads-mobile-flutter/issues/544 
I guess it is not your problem, but I it is useful information.

**Comment by bgoncharuck** [comment]
Thank you for a help, @yuhao900914

**Comment by bgoncharuck** [comment]
If someone want to find a working solution for both Google AdMob and Amplitude or other plugins that need use_frameworks!

Add this to Podfile 
`use_frameworks! :linkage => :static`

**Comment by bgoncharuck** [comment]
@yuhao900914 you can close the issue
It is not issue of Amplitude SDK

**Comment by yuhao900914** [comment]
Thanks @bgoncharuck for the solution!
