### ISSUE TITLE
Problems with JS dep in native android app

### ISSUE THREAD

**Issue by nosovk** [amplitude/Amplitude-Flutter#118]
## Expected Behavior
Adding amplitude package to flutter shouldn't affect build

## Current Behavior
Adding amplitude to an existing flutter app causes native build to fail.

## Possible Solution
We have found this https://github.com/flutter/flutter/issues/70373#issuecomment-758067156
```bash
sed -i '/show allowInterop, allowInteropCaptureThis/d' /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart
```
it helps, but it's not a solution

## Environment
- SDK Version: ^3.10.0
- Flutter Version: ^3.00.0

Build log:
```
error	02-Sep-2022 19:10:03	#80 80.63 [ +796 ms] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:8:3: Error: Can't have modifier 'const' here.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] Try removing 'const'.
error	02-Sep-2022 19:10:03	#80 80.63 [        ]   const _Anonymous();
error	02-Sep-2022 19:10:03	#80 80.63 [        ]   ^^^^^
error	02-Sep-2022 19:10:03	#80 80.63 [        ] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:8:21: Error: Expected a function body or '=>'.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] Try adding {}.
error	02-Sep-2022 19:10:03	#80 80.63 [        ]   const _Anonymous();
error	02-Sep-2022 19:10:03	#80 80.63 [        ]                     ^
error	02-Sep-2022 19:10:03	#80 80.63 [        ] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:9:1: Error: Expected a declaration, but got '}'.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] }
error	02-Sep-2022 19:10:03	#80 80.63 [        ] ^
error	02-Sep-2022 19:10:03	#80 80.63 [+1298 ms] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:22:7: Error: '_Anonymous' isn't a type.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] const _Anonymous anonymous = _Anonymous();
error	02-Sep-2022 19:10:03	#80 80.63 [        ]       ^^^^^^^^^^
error	02-Sep-2022 19:10:03	#80 80.63 [        ] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:8:9: Context: This isn't a type.
error	02-Sep-2022 19:10:03	#80 80.63 [        ]   const _Anonymous();
error	02-Sep-2022 19:10:03	#80 80.63 [        ]         ^^^^^^^^^^
error	02-Sep-2022 19:10:03	#80 80.63 [+1999 ms] /root/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.10.0/lib/web/amplitude_js.dart:5:2: Error: Couldn't find constructor 'JS'.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] @JS('amplitude')
error	02-Sep-2022 19:10:03	#80 80.63 [        ]  ^^
error	02-Sep-2022 19:10:03	#80 80.63 [        ] /root/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.10.0/lib/web/amplitude_js.dart:40:2: Error: Couldn't find constructor 'JS'.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] @JS('amplitude.Identify')
error	02-Sep-2022 19:10:03	#80 80.63 [        ]  ^^
error	02-Sep-2022 19:10:03	#80 80.63 [ +199 ms] /root/.pub-cache/hosted/pub.dartlang.org/js-0.6.4/lib/js.dart:22:30: Error: Method invocation is not a constant expression.
error	02-Sep-2022 19:10:03	#80 80.63 [        ] const _Anonymous anonymous = _Anonymous();
error	02-Sep-2022 19:10:03	#80 80.63 [        ]                              ^^^^^^^^^^
```

**Comment by yuhao900914** [comment]
Hi @nosovk,

I tried to run the following command in my example:
`./gradlew assemble`
`flutter build apk`
`flutter build web`

All got passed. Can you provide more information on how I can reproduce this? How do you run the build?


<img width="1134" alt="Screen Shot 2022-11-04 at 1 21 33 PM" src="https://user-images.githubusercontent.com/13028329/200068878-73cd9b66-2883-4773-b2dc-d6a6ac16c53e.png">

<img width="1102" alt="Screen Shot 2022-11-04 at 1 34 04 PM" src="https://user-images.githubusercontent.com/13028329/200069201-38412c86-873d-44a5-9aa5-c8fabe3d823e.png">



<img width="621" alt="Screen Shot 2022-11-04 at 1 28 32 PM" src="https://user-images.githubusercontent.com/13028329/200068933-6e36825c-99bc-4c9d-9adf-d8fd5f9d54b6.png">

**Comment by sarthakjha889** [comment]
@nosovk I was running into the same problem an hour back. Turns out I was importing the `Amplitude` class from the web variant.  Check the import where ever you're using the `Amplitude` class. The import should be `import 'package:amplitude_flutter/amplitude.dart';` and not `import 'package:amplitude_flutter/web/amplitude_js.dart';`. Hopefully, this will solve your problem.

**Comment by justin-fiedler** [comment]
Hi @nosovk I believe the above solution is correct. Marking as resolved. Please reopen if needed. Thanks!

**Comment by nosovk** [comment]
yep, issue seems to be resolved at current version
