### ISSUE TITLE
Not compatible with latest android gradle plugin

### ISSUE THREAD

**Issue by saurabh-acko** [amplitude/Amplitude-Flutter#119]
The existing gradle dependency has kotlin version `1.3.40` which is not compatible with latest gradle and kotlin plugin. Please upgrade it to latest version of kotlin plugin

**Comment by yuhao900914** [comment]
Hi there, thanks for choosing amplitude. 
We are hesitant to upgrade to the latest version, because of the backward compatibility. 
https://github.com/amplitude/Amplitude-Flutter/issues/73
I will discuss with the team and get back to you.
