### ISSUE TITLE
Override the min_id_lenght value on Flutter

### ISSUE THREAD

**Issue by EsteveAguilera** [amplitude/Amplitude-Flutter#126]
According to the documentation, the user IDs must be strings with a length of 5 characters or more, but this value can be overridden by passing the `min_id_length` option with the request.

I can't find a way to do that on flutter.

Neither the `init` nor the `setUserId` methods accept any option object or parameter to override this value.

**Comment by yuhao900914** [comment]
Hi @EsteveAguilera, thanks for choosing amplitude. 
I think there has a mistake in docs, the native android, and native ios do not support overwriting min_id_length.
We will fix that soon.

**Comment by EsteveAguilera** [comment]
Oh, thanks! I cole the issue

**Comment by stargt** [comment]
Fixed?

**Comment by EsteveAguilera** [comment]
Nothing has to be fixed, as @yuhao900914 pointed out, it was just a mistake in the docs, native android and ios do not support overwriting the `min_id_lenght`
