### ISSUE TITLE
Invalid API key, make sure your API key is correct in initialize()

### ISSUE THREAD

**Issue by MapleNoise** [amplitude/Amplitude-Flutter#128]
## Expected Behavior
I Have this error when use `logEvent` function on Flutter :
`Invalid API key, make sure your API key is correct in initialize()` on Android
`ERROR: Connection response received:400, invalid_api_key` on iOS

## Current Behavior
I have always this error on 3.7.0 and 3.11.0 version when I call `logEvent`, and it works randomly on 3.2.1 version.

## Possible Solution
Here is my code (not very difficult) and all my test for changes to try fix :

```
static final Amplitude analytics = Amplitude.getInstance(instanceName: "name app"); //change multiple name

initAmplitude() async {
    await MyApp.analytics.init("My api key", userId: MyApp.auth.currentUser.uid); //test to remove userId and set with setUserId function
    await MyApp.analytics.setServerZone("EU"); //or setServerUrl(""https://api.eu.amplitude.com""); with 3.2.1 version
     MyApp.analytics.logEvent(
          "app_launched",
          eventProperties: {},
        );
  }
```
  
  I test to add `useAppSetIdForDeviceId` because I've always this log :
`Google Play Services SDK not found for app set id!` as expected here : https://github.com/amplitude/Amplitude-Flutter/issues/98#issuecomment-1043243868

But nothing change, always this 2 errors.

Of course I verify thats my API key is correct from my settings dashboard

## Environment
- SDK Version: 3.11.0, 3.7.0 and 3.2.1
- Flutter Version: 2.10.5
- Device: Any Android and iOS
- Device OS and Version: all versions 

What am I doing wrong?
Thanks

**Comment by qingzhuozhen** [comment]
Hi @MapleNoise, thanks for choosing Amplitude. One quick thing to confirm is, is your project in Amplitude EU? If not, then set the server zone to EU would not work, and can't identify the api key.

**Comment by MapleNoise** [comment]
Thanks you for you reply,

You mean the timezone in the project parameters ?

<img width="568" alt="Capture d’écran 2022-11-29 à 08 40 03" src="https://user-images.githubusercontent.com/1905622/204468424-eb644031-8527-4043-9197-d289a1343be2.png">

Yes it is

Edit : It will be ok when I remove `setServerZone("EU")`

**Comment by qingzhuozhen** [comment]
Hi @MapleNoise, the server zone is not referring to project parameters. If removing the server zone works for you, then it means the project here is not Amplitude EU project. Amplitude EU data center lives separately, and you need to create a project in Amplitude EU. Then you can use the EU project api key and set server zone in SDK.
