### ISSUE TITLE
What is the proper way to track screens? 

### ISSUE THREAD

**Issue by EsteveAguilera** [amplitude/Amplitude-Flutter#133]
I've read the Flutter SDK documentation, and I've not seen anything related to tracking the screens.

Is there a specific way to do it? 

On Firebase we can use `FirebaseAnalytics().setCurrentScreen(screenName: 'Example1');`

Or should we use regular events with properties?

**Comment by kevinpagtakhan** [comment]
Hi @EsteveAguilera, thank you for choosing Amplitude. Yes, you would have to use `logEvent` method and pass in your event name and optional event properties. Looking at Firebase docs [here](https://developers.google.com/android/reference/com/google/firebase/analytics/FirebaseAnalytics#:~:text=setCurrentScreen(Activity,SCREEN_VIEW%2C%20params)%20instead.), and it appears that `setCurrentScreen` is already deprecated and the recommended way is to use the `logEvent` method as well.

**Comment by EsteveAguilera** [comment]
Thank you so much for the clarification @kevinpagtakhan! Will use the `logEvent` then.
