### ISSUE TITLE
Can't find trackingOptions in flutter

### ISSUE THREAD

**Issue by larryhuang** [amplitude/Amplitude-Flutter#138]
Can't find trackingOptions in flutter to skip some default properties

**Comment by Mercy811** [comment]
Hi @larryhuang, Amplitude Flutter SDK v3.x wraps Amplitude maintenance Android SDK which doesn't support `trackingOptions`. 

We are updating the Flutter SDK to wrap on the latest Android and iOS SDKs. [amplitude_flutter: 4.0.0-beta.1](https://pub.dev/packages/amplitude_flutter/versions/4.0.0-beta.1) is released as a beta version. Here is the [migration guide](https://www.docs.developers.amplitude.com/data/sdks/flutter/migration/). I will have a full reference doc soon. Here is the [example app](https://github.com/amplitude/Amplitude-Flutter/blob/beta/example/lib/my_app.dart#L42-L48). 

Here is an example to set trackingOptions
```
    analytics = Amplitude(
        Configuration(
            apiKey: widget.apiKey,
            logLevel: LogLevel.debug,
            defaultTracking: DefaultTrackingOptions.all(),
            trackingOptions: TrackingOptions(
              ipAddress: false,
              language: false,
            )
        )
    );
```
Here is the source file: https://github.com/amplitude/Amplitude-Flutter/blob/21c7f09fccacad41d8183f6c3947d3be07740360/lib/tracking_options.dart#L1-L8
