### ISSUE TITLE
Past data updated todays without any forced customizing

### ISSUE THREAD

**Issue by whatamelon** [amplitude/Amplitude-Flutter#14]
My team just figure out that past data can updated in spite of days ago.
When we service web page with amplitude javascript previously, this case does not happened.
So, my company asking for why this situation happening.
And we've got answered like this; ' This is flutter issue. In flutter library, event fullfil with 30 events then it goes to server. '

I think this can be a little bit critical issue.
I guess, according to that answer, we cannot see whole data with amplitude because if someone's events are less than 30, then we can't get any events with that customer.

So, I wish that amplitude flutter library enhanced as soon as possible.

Always thanks to your service :D

**Comment by haoliu-amp** [comment]
Hello! I don't think I fully understand your question. Are you saying old events older than 30 days not getting uploaded?

**Comment by whatamelon** [comment]
Sorry for late close issue. My team just ask your official team and get answer that use uploadEventes method. Thx :D
