### ISSUE TITLE
IP and location are transmitted even though CoppaControl is activated

### ISSUE THREAD

**Issue by nblum37** [amplitude/Amplitude-Flutter#148]
## Expected Behavior
We expect the location and the IP address to be masked when Coppa control is activated. 

## Current Behavior
However, both data points are still tracked, sent to the server by the framework, and visible for each event.

## Steps to Reproduce
Amplitude is initialized the following way
```
  Future<void> init() async {
    await _analytics.init(apiKey);
    await _analytics.setServerZone('EU');
    await _analytics.enableCoppaControl();
  }
```
Please let us know if there are other ways to hide data protection-sensitive data.

## Environment
- SDK Version: 3.15.0
- Flutter Version: 3.10.6
- Device: iPhone7
- Device OS and Version: iOS 15.7.7

**Comment by Mercy811** [comment]
Hi @nblum37, have you ever sent IP and location before enabling COPPA? If so, Amplitude's backend uses history IP and location data. Could you log the payload of events sent to see if IP and location are include? If not, it means COPPA is set successfully. You can simply test with another user id or create another project and send events to the new project.

**Comment by nblum37** [comment]
No, so COPPA was enabled starting from the very first attempt to include Amplitude. I see the same behavior if I change to a user that was not logged before, meaning also the location and IP are tracked.
As the Amplitude traffic is sent via a native package, it is not straightforward to intercept the packages before being HTTPS encrypted. Does the framework offer the possibility to enable verbose logging in the console? Or how can I log the payload?

EDIT: Is it possible that clearUserProperties() resets the COPPA setting? If I enable COPPA again after clearing the user properties, it seems to work fine. The only question would be then, if also other settings like server region and so on need to be set again, as well?

**Comment by nblum37** [comment]
Is it possible that `clearUserProperties()` can reset the COPPA setting?

**Comment by Mercy811** [comment]
Hi @nblum37, could you share your project link so that I can check if Ip and location are in raw requests. `clearUserProperties()` internally send a `$clearAll` event to clear all history user properties including region in DB so it should work.

**Comment by nblum37** [comment]
Thanks for the reply. I sent the link to your GitHub e-mail address.

So it seems to keep COPPA enabled if I use the following code to set user properties
```
  Future setUserId({@required String? id}) async {
    id = id?.split('_').lastOrNull ?? id;

    await _analytics.enableCoppaControl();
    await _analytics.setUserId(id);
  }
```

**Comment by Mercy811** [comment]
Hi @nblum37, thanks for sending you project link. I've checked that for user `830acde4-ef26-4411-a9b1-150957cb3a83`, IP address is not tracked in the event payload. Note that COPPA covers "geolocation information sufficient to identify street name and name of a city or town" which means if you enable it, Amplitude will not track Ip address, city, latitude, longitude. ([code reference](https://github.com/amplitude/Amplitude-Android/blob/4e37e0f2d21c437af2b4f4bb58520b061a21a2be/src/main/java/com/amplitude/api/TrackingOptions.java#L21) and [doc](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#coppa-control)). If you want to disable tracking country and city, please follow this [doc](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#disable-tracking). 

Looks like the SDK works as expected as far as I investigate. Could you share a link of the event/user if there is a special case tracking COPPA info.

For your last comment, did you solve it by putting `enableCoppaControl()` inside?
