### ISSUE TITLE
NoSuchMethodError: The method 'addObserver' was called on null

### ISSUE THREAD

**Issue by nomyzs** [amplitude/Amplitude-Flutter#15]
`2019-04-26 15:37:43.734 4712-4773/app.realtimegames.fanclash E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'addObserver' was called on null.
    Receiver: null
    Tried calling: addObserver(Instance of 'Session')
    #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
    #1      new Session._internal (package:amplitude_flutter/src/session.dart:15:29)
    #2      new Session (package:amplitude_flutter/src/session.dart:9:25)
    #3      new AmplitudeFlutter (package:amplitude_flutter/src/amplitude_flutter.dart:15:15)
    #4      new Analytics (package:fanclash/analytics.dart:11:19)
    #5      main (package:fanclash/main.dart:23:3)
    #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
    #7      _rootRun (dart:async/zone.dart:1124:13)
    #8      _CustomZone.run (dart:async/zone.dart:1021:19)
    #9      _runZoned (dart:async/zone.dart:1516:10)
    #10     runZoned (dart:async/zone.dart:1500:12)
    #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
    #12     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
    #13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)`

**Comment by alexwdaniel** [comment]
@nomyzs Hi, thanks for your feedback. Can you provide some additional context about how you encountered this error? It would be very helpful in diagnosing the issue.

**Comment by nomyzs** [comment]
Aha! Ok, my bad guys. I tried initializing Amplitude in `main` method, before running any app widget. That caused the crash I believe. 
Sorry, was too quick to report :)
So happy I can use easily amplitude on flutter app! Thank you for that :)

**Comment by alexwdaniel** [comment]
Yes, that would cause it to crash. Currently, the plugin can only be used inside flutter's main isolate. This appears to be a known issue with plugins that rely on platform channels.

https://github.com/flutter/flutter/issues/13937
