### ISSUE TITLE
amplitude_flutter plugin not install my .yaml file 

### ISSUE THREAD

**Issue by krupalieBizTrait** [amplitude/Amplitude-Flutter#153]
## Summary

amplitude_flutter plugin code add in native file ?

**Comment by justin-fiedler** [comment]
Hi @krupalieBizTrait thanks for choosing Amplitude.

The Amplitude Flutter SDK is built on top of the native Amplitude Android SDK and iOS SDKs. See [more details in our documentation](https://www.docs.developers.amplitude.com/data/sdks/flutter/#configuration). Hope this helps!
