### ISSUE TITLE
Amplitude is logging wrong User properties for flutter SDK

### ISSUE THREAD

**Issue by viveksaruk** [amplitude/Amplitude-Flutter#159]
## Expected Behavior
It should not set any property if not applied.

## Current Behavior
It is applying wrong properties if not set any property/identity

## Steps to Reproduce
Below is the screenshot where we can see the Subscriber status getting wrongly applied. (The remaining columns are the params we send in the analytics call) 

<img width="1192" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/30343280/9f69a763-358e-4c7e-a513-b068b05bfb64">

In code, we either set the identity/property as Active or nothing as a subscriber_status. But somehow the wrong are getting applied or applied as an array.

<img width="1620" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/30343280/cbd1d37e-a84b-428d-95a1-d84fd2bdda58">

## Environment
- Flutter Version:  amplitude_flutter: 3.13.0

**Comment by justin-fiedler** [comment]
Hello @viveksaruk thanks for using Amplitude.

I tested setting/clearing user properties from the Flutter SDK using [our example app here](https://github.com/amplitude/Amplitude-Flutter/blob/main/example/lib/my_app.dart) and it works as expected.
<img width="884" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/5790872/5a90e437-006c-4cd4-9929-3b3900cb32df">

<img width="523" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/5790872/e254a463-1aea-4433-9739-cc1ad4fbe766">

Your output shows a majority of the events have the expected value you provided of `Active`.
<img width="681" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/5790872/ecf50552-2508-4f67-95ab-66aba17c6e79">

Is it possible you are setting these values in another location? How are the other non-active values being set (e.g. `In Grace Period`, `Not Started`)?

**Comment by viveksaruk** [comment]
@justin-fiedler We are sending only Active value. Neither we are sending In Grace Period, Not Started and remaining non-active values too. 
Could it be possible when we remove value in the line below from a code snippet I shared above, SDK apply it?
 `Identify identify = Identify()..remove('subscriber_status', 'Active');`

**Comment by justin-fiedler** [comment]
Hi @viveksaruk, user properties are shared across platforms. Is it possible that another SDK (e.g. web) is setting the other values?

If you provide a link to your project (or your org name/id) I can take a look and try to find how those values are being ingested.

Thanks

**Comment by justin-fiedler** [comment]
Is this happening on a specific platform? iOS/Android/Web?

**Comment by viveksaruk** [comment]
@justin-fiedler Org ID is 185225 
Yes,  for iOS/Android it is happening.

**Comment by justin-fiedler** [comment]
Hi @viveksaruk I checked a few of your projects. I was only able to find `subscriber_status` in the "Development" project.

I created a chart grouped by `Library` to show what sources are potentially setting the non-`Active` values. It shows events being injested from the Amplitude Browser SDK (`amplitude-ts/1.10.2`) and the HTTP API. My guess is that another team is setting these values, not the Flutter SDK.

<img width="1234" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/5790872/8efc2068-42cf-4bd8-b4d3-eed92aa96c94">

Hope this helps! Let me know if there is another project I should check.

**Comment by viveksaruk** [comment]
@justin-fiedler I found this in Production but it has **User Subscriber Status** instead of **subscriber_status** (we send this from mobile which can be seen in the code snippet shared above) 
and non Active values can be seen from mobile too
<img width="1790" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/30343280/812789fe-7d5f-4dc6-bc27-5785c2be1a62">

**Comment by Mercy811** [comment]
Hi @viveksaruk, it seems that it is set by imported events from Braze. There is an example
- [Event 1](https://app.amplitude.com/analytics/mcclatchy/project/412949/search/amplitude_id%3D584003454046?collapsed=true&sessionHandle=-B_Y1OQsBw_If5UYRe_Bk0V_fe8b8327-b728-5cb8-a455-b90ef521a179&eventId=b4d1248e-5b29-402d-a634-abf714794ae1) with subscriber status as active 
- [Event 2](https://app.amplitude.com/analytics/mcclatchy/project/412949/search/amplitude_id%3D584003454046?collapsed=true&sessionHandle=-B_Y1QKsYI_If5UYRe_Bk0V_fe8b8327-b728-5cb8-a455-b90ef521a179&eventId=d97135db-6fc3-4c33-92ab-9fcb58b0532a) right after Event 1 has subscriber status as "
In Grace Period"

Also `User Subscriber Status` is a [merged property ](https://app.amplitude.com/data/mcclatchy/All%20McClatchy%20-%20Production/properties/main/latest/user/User%20Subscriber%20Status-42003)with `subscriber_status`. 
<img width="637" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/31029607/0b023a82-ef5d-468b-ae0c-df61e125e063">

Close this issue as it's not a SDK problem.
