### ISSUE TITLE
Unusually Long Sessions

### ISSUE THREAD

**Issue by andrewkimjoseph** [amplitude/Amplitude-Flutter#160]
## Current Behavior
Our Flutter app is logging unusually long sessions, as in the following screenshots of a sample user:

<img width="494" alt="Screenshot 2023-11-15 at 10 42 33" src="https://github.com/amplitude/Amplitude-Flutter/assets/91619206/cf975b24-2f9d-4420-ab98-077e6d3e0ff1">

- Session lasted a whole day.

## Our Setup
We have this class, `EventLogger`, that we use to create the instance and initiate the SDK:
```
class EventLogger extends EventData {
  ...
  Amplitude amplitudeAnalytics =
      Amplitude.getInstance(instanceName: name);

  void initializeAmplitude() {
    amplitudeAnalytics.init(dotenv.env["AMPLITUDE_API_KEY"]!);
  }
 ...
}
```

Then, we call the `initializeAmplitude` method in the `main` method:
```
void main() async {
 ...

  EventLogger().initializeAmplitude();

 ...
}
```

## The Issue
Three possible reasons:
> - We are doing something incorrectly with our implementation
> - The platform SDKs have issues
> - We have other services in our platform that are affecting the SDK

## Environment
- SDK Version: `^3.13.0`
- Flutter Version: `3.13.9`
- Device: `Redmi Phone (one example)`
- Device OS and Version: `Android 12`

**Comment by Mercy811** [comment]
Hi @andrewkimjoseph, the long session issue should be fixed in [`3.15.0`](https://github.com/amplitude/Amplitude-Flutter/releases/tag/v3.15.0). Could you upgrade and see if it happens again? Thanks
