### ISSUE TITLE
DefaultTrackingOptions configuration is missing on Flutter SDK

### ISSUE THREAD

**Issue by sky1095** [amplitude/Amplitude-Flutter#161]
## Summary

The DefaultTrackingOptions configuration is missing on Flutter SDK, but its possible on both Android and iOS SDK

Android:
<img width="855" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/16065933/3d0a9d44-0036-4a82-afbd-7a9a69bcde83">

iOS:
<img width="852" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/16065933/877cb4d3-8e16-4d3b-a0ed-6c6a2c3b923b">

## Motivations

This will help to add default tracking options seamlessly on Flutter apps.

**Comment by qingzhuozhen** [comment]
Hi @sky1095, thanks for raising this! The current version of Flutter SDK is based on our legacy Android and iOS SDKs. We are working on upgrading the Flutter SDK that will be based on the updated SDKs and will provide this default tracking option. Please stay tuned when we release the new Flutter SDK version! cc @Mercy811

**Comment by sky1095** [comment]
Thanks for the update @qingzhuozhen.
Where can I track this SDK migration changes?

**Comment by Mercy811** [comment]
Hi @sky1095, we will update the github README file and share the new breaking change version on Amplitude community. I will also tag you under this thread 😀

**Comment by Mercy811** [comment]
Hi @sky1095, Flutter 4.x Beta is available now with `defaultTrackingOptions` available in the configuration and here is the doc https://www.docs.developers.amplitude.com/data/sdks/flutter-4/#tracking-default-events
