### ISSUE TITLE
Support Kotlin 1.8

### ISSUE THREAD

**Issue by ch-linhphan** [amplitude/Amplitude-Flutter#163]
## Summary

By upgrade the kotlin embedded version or increase android build gradle to 8.0, I got this build error

> Execution failed for task ':amplitude_flutter:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.

## Motivations
Latest release of some libaries (eg: Firebase, reCaptcha) required kotlin 1.8 version

**Comment by QPAYRE** [comment]
Same problem here
@ch-linhphan if you found a solution please let met know.

**Comment by AlexPopaUpcode** [comment]
I have also encountered this issue and I don't have a solution yet

**Comment by AndreHaueisen** [comment]
This is blocking a prod release for us. Any updates?

**Comment by marcuscorreasmash** [comment]
same problem here.. any update please?

**Comment by otopba** [comment]
Same here

**Comment by gothedistance** [comment]
Same Here...

**Comment by putnokiabel** [comment]
#202 should fix the issue.

Until it's merged (or the issue is otherwise fixed) and there's a new release, you can use this as a workaround
```yaml
amplitude_flutter:
    git:
      url: https://github.com/putnokiabel/Amplitude-Flutter.git
      ref: jvm-target
```
