### ISSUE TITLE
Missing NSPrivacyTracking in PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by Mihai-Moniflo** [amplitude/Amplitude-Flutter#189]
## Expected Behavior
The app doesn't get any warnings from Apple.

## Current Behavior
The app receives the following warning when sending for review to Apple:

> ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/AmplitudeSwift.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files. 

We can't complete our weekly release schedule due to this issue.

## Possible Solution
Add the following snippet to *PrivacyInfo.xcprivacy*:
```
<key>NSPrivacyTracking</key>
<true/>
```

## Steps to Reproduce
1. Add the *amplitude_flutter: ^4.0.0-beta.3* plugin to your app.
2. Upload the app to App Store Connect and send for review.
3. You'll receive an email with the warning listed above.

## Environment
- SDK Version: 4.0.0-beta.3
- Flutter Version: 3.19.3
- Device: not relevant
- Device OS and Version: not relevant

**Comment by nikolaydymura** [comment]
Experiencing the same problem as well

**Comment by crleona** [comment]
Hi @Mihai-Moniflo, if you're using 4.0.0-beta.3, you should just be able to run `pod update` to pull in the latest updates to the Amplitude-Swift SDK which have already fixed this issue. (You can check your Podfile.lock for Amplitude-Swift 1.4.5).

**Comment by Mihai-Moniflo** [comment]
Thanks for the answer! I just saw the PR that removed the NSPrivacyTrackingDomains. My bad :(. However, from what I see, the following file
https://github.com/amplitude/Amplitude-Flutter/blob/beta/ios/amplitude_flutter.podspec points to Amplitude-Swift 1.4.4. Shouldn't it be pointing to 1.4.5 in this case? `pod update` doesn't update Amplitude-Swift to 1.4.5 due to this reason.

**Comment by Mercy811** [comment]
Hi @Mihai-Moniflo, we already have a ticket for this. I will work on this and will keep you updated.

**Comment by Mercy811** [comment]
Hi @Mihai-Moniflo, I confirm that `pod update` should update to use Amplitude-Swift 1.4.5.
![image](https://github.com/amplitude/Amplitude-Flutter/assets/31029607/bf60499c-961f-4303-90c2-4476d01e61e1)
