### ISSUE TITLE
How to add VersionCode in amplitude events

### ISSUE THREAD

**Issue by Dr-Usman** [amplitude/Amplitude-Flutter#190]
Hello i have integrated the amplitude analytics in flutter application. and It's working great and record each event properly. 
I have added default tracking configuration as well.  It shows version number of the app in dashboard and in event detail/user look up page. But is there any way to add or configure to show versionCode as well. 

**Configuration**
```dart
static final Amplitude amplitude = Amplitude(
    Configuration(
      apiKey: apiKey,
      defaultTracking: DefaultTrackingOptions.all(),
      appVersion: locator<ConfigBloc>().versionNumber,
    ),
  );
```

Pubspec.yaml => `version: 0.0.7+8`

**Dashboard**
<img width="520" alt="Screenshot 2024-05-28 at 12 38 58 PM" src="https://github.com/amplitude/Amplitude-Flutter/assets/48102385/343babc5-1ff6-41a7-96f6-5a78e98f3534">

**Comment by Mercy811** [comment]
Hi @Dr-Usman, currently [plugins](https://www.docs.developers.amplitude.com/data/sdks/sdk-architecture/#plugins) are not supported. We will add plugin support in the future but currently no ETA for it. You can add `versionCode` by `track()` to set it as a event property or by `identify()` to set it as a user property. 

```
amplitude.track(BaseEvent('test event', eventProperties: {'versionCode': 1}));

final Identify identify = Identify()
      ..set('versionCode', 1);
amplitude.analytics.identify(identify);
```

**Comment by Dr-Usman** [comment]
@Mercy811 Thank you so much for your response and assistance.  There's one more thing i would like to ask Experiment SDK for Flutter? There's support for react native and other client and server sides but i couldn't find for flutter, only analytics SDK support for Flutter. When we are expecting to have an Experiment SDK for Flutter as well?

**Comment by Mercy811** [comment]
Hi @Dr-Usman, we don't have plan for Experiment Flutter SDK unfortunately.
