### ISSUE TITLE
Update dependency on js package to 0.7.x

### ISSUE THREAD

**Issue by john-paradym** [amplitude/Amplitude-Flutter#191]
## Summary

The js dependency in pub spec.yaml is using an old version of the js package

Even the 4.0.0 beta is using js 0.6.3, which is over 3 years old now

## Motivations

We have other packages in our app that already have updated to js 0.7.1, but I cannot update them (without hacking a dependency override) until Amplitude updates to the later versions of js

**Comment by izaaz** [comment]
Thank you for the feedback @john-paradym. We haven't added browser support for the v4.0 SDK yet (it still contains the old browser support from the main branch). But i'll add a note to that feature to make sure this gets updated.

**Comment by GP4cK** [comment]
Actually it would be good to remove the dependency on `js` and use `dart:js_interop` instead to enable compilation to WASM. See: https://github.com/amplitude/Amplitude-Flutter/issues/197

**Comment by suiebay** [comment]
Any update or changes?

**Comment by vilorel** [comment]
Any updates? It's 3 months now and many highly popular packages have already moved to js: 0.7.1 which now represents a blocker for us to adopt. 
I tried to override the dependency, but it breaks the Android build.

**Comment by vilorel** [comment]
@izaaz could you or someone from the team share a status update? This is a blocker and has been pending for some timeno now. Also, although we keep asking, there are no updates either. Thanks.

**Comment by Saed-Eltalwy** [comment]
@izaaz  We are facing the same block as we transition to Amplitude, but we already have some dependencies using js: 0.7.1.

**Comment by chungdaniel** [comment]
Hey! I've upgraded the dependency of `package:js` to ^0.7.0 in 3.16.5 with #213 / #215. We will look into removing `js` and using `dart:js_interop` in v4.
