### ISSUE TITLE
How to set the Language user property

### ISSUE THREAD

**Issue by bjartebore** [amplitude/Amplitude-Flutter#193]
## Summary

In the app we are developing the users can change the language within the app. I want to update the language user property, but it does not seem to update the system value of the property. Is there a correct way to update this value?

I am using the following code to set the userProperty
```dart
  Future<void> setLanguage(String language) async {
    return _amplitude.setUserProperties({"Language": language});
  }
```

This is how it shows in the event stream
<img width="579" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/1978938/acdc3027-1777-471b-827e-8fbb0b6d1c8a">

I am using flutter_amplitude v3.16.2 and Flutter v3.22.2 iOS and Android

**Comment by Mercy811** [comment]
Hi @bjartebore, the SDK should track language user property by default, for example, the underlying iOS SDK https://github.com/amplitude/Amplitude-iOS/blob/bfdec453a31fd35942a619ef472fcf2f09e2313a/Sources/Amplitude/Amplitude.m#L815-L816. The default user properties should starts with an Amplitude icon like the screenshot.
![image](https://github.com/amplitude/Amplitude-Flutter/assets/31029607/b9ae5fab-d3e6-4f60-a947-f7a1450a9273)

However, if you wish to set your own user properties, you can follow https://amplitude.com/docs/sdks/analytics/flutter/flutter-sdk#set.

**Comment by Mercy811** [comment]
Close this issue as not hearing back.
