### ISSUE TITLE
Amplitude Flutter v4.0.0 Beta 4 does not work on Android: Unresolved reference library_

### ISSUE THREAD

**Issue by mihaiborcansst** [amplitude/Amplitude-Flutter#194]
## Expected Behavior
Project compiles without errors.

## Current Behavior
.pub-cache/hosted/pub.dev/amplitude_flutter-4.0.0-beta.4/android/src/main/kotlin/com/amplitude/amplitude_flutter/FlutterLibraryPlugin.kt:15:31 Unresolved reference 'library_' when trying to run the app on an Android device/emulator.

## Possible Solution
Use `${library}_${event.library}` instead of `$library_${event.library}` at https://github.com/amplitude/Amplitude-Flutter/blob/b9b7c5d589bd9810d773a5f921b98d92cc90b68e/android/src/main/kotlin/com/amplitude/amplitude_flutter/FlutterLibraryPlugin.kt#L15

## Steps to Reproduce
1. Add the latest beta version to any flutter project.
2. Run the app on an Android device/emulator.

## Environment
- SDK Version: 4.0.0-beta.4
- Flutter Version: 3.22.1
- Device: not relevant
- Device OS and Version: not relevant

Am I missing something?

**Comment by Mercy811** [comment]
Hi @mihaiborcansst, `4.0.0-beta.5` should fix this.

**Comment by mihaiborcansst** [comment]
Thank you, @Mercy811! Sorry for the late answer. I'll close this issue now.
