### ISSUE TITLE
Set useDynamicConfig for China Mainland?

### ISSUE THREAD

**Issue by thomasgazzoni** [amplitude/Amplitude-Flutter#23]
I use amplitude for my flutter project, by checking the reports we found out we can't get any analytics report from Mainland China, by checking the docs I found this:

![image](https://user-images.githubusercontent.com/12007170/93969095-ab120880-fd9d-11ea-8103-76e1ab1b70f1.png)

But so far `Amplitude-Flutter` do *not expose* this `useDynamicConfig` configuration.

I try to change the iOS code but still the `Amplitude.instance` still do not have any `useDynamicConfig` method/props.

Is there any sulutions?

**Comment by haoliu-amp** [comment]
It's only available for native iOS and Android SDKs for now. Now api2.amplitude.com should work for every region, so it's fine. We will add it soon to Flutter.

**Comment by thomasgazzoni** [comment]
Hi @haoliu-amp, thanks for the reply, so basically I should use `setServerUrl` and set `api2.amplitude.com` to get reports from China Mainland, right? need to add https (https://api2.amplitude.com) ?

**Comment by haoliu-amp** [comment]
You don't need to make any changes if you use the latest version, it's `https://api2.amplitude.com` by default now.

**Comment by thomasgazzoni** [comment]
I am using the latest version `2.2.1`, but if I don't explicitly set the `serverUrl` to api2.amplitude.com, I won't receive any data from Mainland China.

Anyway the issue can be close since using api2.amplitude.com solved my problem.

**Comment by haoliu-amp** [comment]
Ah, sorry, it doesn't set api2 by default. We only expose the `setServerUrl` API.
