### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by nishiths23** [amplitude/Amplitude-Flutter#26]
## Expected Behavior
App should not crash

## Current Behavior
App is crashing

## Possible Solution
userId is passed to the parameters map instead of startNewSession

## Steps to Reproduce
1. call method setUserId with startNewSession true
2. app crash is observed on iOS

## Environment
- SDK Version: 2.2.1
- Flutter Version: 1.22.2
- Device: any iOS device
- Device OS and Version: any iOS device

**Comment by haoliu-amp** [comment]
Thanks @nishiths23 !
