### ISSUE TITLE
Event properties are not sent to Amplitude

### ISSUE THREAD

**Issue by MElkady** [amplitude/Amplitude-Flutter#32]
I'm trying to log an event with properties using the sample code in README file:
```
analytics.logEvent(name: 'add_friend', properties: { 'key': 'value' });
```

When I check Amplitude dashboard, I found that the event was sent but properties are not sent

**Comment by mockturtl** [comment]
It's a typo.  If you wrap your data under the appropriate key `{'event_properties': props}`, it shows up in the dashboard.  See the [tests](https://github.com/amplitude/Amplitude-Flutter/blob/master/test/amplitude_flutter_test.dart#L152).

It would be nice to see properties demonstrated in `example/`, too.

@ingar Want a PR?

**Comment by ingar** [comment]
That's right @mockturtl, it's a typo -- the common use case for a client using the `properties` param is for event properties.  I will go ahead and update the docs.

You are always welcome to open PRs!

**Comment by priezz** [comment]
Please bump the plugin version to have the updated docs at https://pub.dev/packages/amplitude_flutter
