### ISSUE TITLE
com.amplitude.api.AmplitudeClient: context cannot be null, set context with initialize() before calling logEvent()

### ISSUE THREAD

**Issue by blaizechuang** [amplitude/Amplitude-Flutter#32]
## Expected Behavior

logEvent() should be worked correctly

## Current Behavior

Got exception after logEvent() function

## Possible Solution

According to the log, set context correctly in amplitude sdk can fix this issue.

## Steps to Reproduce
 

Build apk with flutter 1.22.4 and invoke logEvent by amplitude.dart.

## Environment
- SDK Version: 2.2.3
- Flutter Version: 1.22.4
- Device: Pixel 3
- Device OS and Version: Android 11

**Comment by blaizechuang** [comment]
Sorry, it's my fault.
After calling init() in new plugin version, it works.

**Comment by rahi0** [comment]
> Sorry, it's my fault.
> After calling init() in new plugin version, it works.

I am having the same problem for my release apk. But debug app working correctly. Paypal button is not loading for release apk. While it's working for the dubg app
```
2021-04-15 11:28:38.392 7682-7780/com.example.flutterkotlinpypl E/com.amplitude.api.AmplitudeClient: context cannot be null, set context with initialize() before calling logEvent()
2021-04-15 11:28:38.396 7682-7780/com.example.flutterkotlinpypl E/nxoEvents: fire: No one listening to the event of type INSTRUMENTATION_SENT. 
```

**Comment by junyou131** [comment]
Have you solved your problem?

**Comment by junyou131** [comment]
@blaizechuang Have you solved your problem?

**Comment by blaizechuang** [comment]
@junyou131 Yes, the root cause is I forgot to call the init() after creating the Amplitude object

**Comment by Gabriel-sys-hub** [comment]
Im having the same issue, any1 else know to resolve this ? 
`E/com.amplitude.api.AmplitudeClient( 5900): context cannot be null, set context with initialize() before calling logEvent()
`

Im calling like this:

 static Future<void> initAmplitudeAnalytics() async {
    final String amplitudeKey = dotenv.env["AMPLITUDE_KEY"]!;

    final Amplitude analytics = Amplitude.getInstance(instanceName: "Project");


    analytics.init(amplitudeKey, userId: 'teste');

    Amplitude.getInstance().trackingSessionEvents(true);
  }

**Comment by iqra-padela** [comment]
You need to provide the instance name when logging events. 

```
analytics.trackingSessionEvents(true);
analytics.logEvent('my event' );

```
OR
```
 Amplitude.getInstance(instanceName: "Project").logEvent( 'my event');
```

**Comment by chhs2131** [comment]
> You need to provide the instance name when logging events.
> 
> ```
> analytics.trackingSessionEvents(true);
> analytics.logEvent('my event' );
> ```
> 
> OR
> 
> ```
>  Amplitude.getInstance(instanceName: "Project").logEvent( 'my event');
> ```

<br/>

great! It works for me!

```dart
final Identify identify = Identify()
  ..set('gender', 'female')
  ..set('age',20);
Amplitude.getInstance(instanceName: name).identify(identify);
```

<img width="1161" alt="image" src="https://github.com/amplitude/Amplitude-Flutter/assets/10378777/2f2a4a0d-629c-4c05-a834-b418b8a82276">
