### ISSUE TITLE
Migrated from native sdk, lost all data continuity

### ISSUE THREAD

**Issue by andreidiaconu** [amplitude/Amplitude-Flutter#34]
Was previously using https://github.com/Evally/flutter_amplitude and had 1y worth of data using it. That implementation is using native sdk libraries. When I saw that amplitude had an official flutter implementation, I simply switched libraries.

- I lost all continuity. All my users "seem" new. I do not have an id system and was relying on amplitude ids for tracking.
- Users no longer have properties they used to have:
  - Language
  - Device Type
  - OS
  - Carrier
  - Device ID is also different (not sure if relevant)

Luckily some user properties I use (2 of which are unique ids from other systems) do have continuity and if I ever need to see previous activity for one user, I can interogate for those properties, but other than that, having Amplitude believe every user is a new one ruined all my funnels and dashboards.

Just for the record, I consider a dart implementation better since it also works well on the web, desktop or wherever else flutter ends up existing. You could:

1. Inform people that migrating from https://github.com/Evally/flutter_amplitude or native sdks is problematic and possibly also offer solutions for migrating gracefully
2. Include the data that is missing (at least language).

If you have any advice on how to unite the duplicated users at this point, I would appreciate any help.

**Comment by haoliu-amp** [comment]
Hey, have you tried latest SDK 1.1.0? Can you check which properties that you want are missing?

I think point 1 makes sense for sure, we will include that into an onboarding doc.

**Comment by haoliu-amp** [comment]
Closing it since no response
