### ISSUE TITLE
Why minimal ios deployment target is 10?

### ISSUE THREAD

**Issue by raapperez** [amplitude/Amplitude-Flutter#34]
## Summary
I understand that the usage was very low. But my company needs to support ios 9+.
Is there any reason to no support iOS 9?

**Comment by haoliu-amp** [comment]
Thanks for reaching out. Yes, we noticed that ios 9 market share was pretty small (<1%) in 2020. That's why we drop the support for it.

**Comment by raapperez** [comment]
Thanks for the answer. In our case we really need to support this small market share.
Is there a workaround to use the new version of amplitude_flutter keeping the support to ios 9 users?

**Comment by haoliu-amp** [comment]
I guess you can try to modify our SDK setting to get iOS 9 supported and directly use your own version of it.
