### ISSUE TITLE
get device ID

### ISSUE THREAD

**Issue by JideGuru** [amplitude/Amplitude-Flutter#36]
## Summary

How can I get the device ID with this SDK? It's possible in iOS http://amplitude.github.io/Amplitude-iOS/Classes/Amplitude.html#//api/name/getDeviceId.

**Comment by funkju** [comment]
Same question.

**Comment by yuhao900914** [comment]
Thanks for the feature request. I will work on this soon.

**Comment by yuhao900914** [comment]
Hi @JideGuru and @funkju. Want to give you guys an update that the deviceId and sessionId are able through getDeviceId() and getSessionId() API. Please check out our new release v3.1.0. 
Thanks.
