### ISSUE TITLE
Session events tracking

### ISSUE THREAD

**Issue by mrserfr** [amplitude/Amplitude-Flutter#36]
Hello!
I need to track session events, but I can't do this in Flutter sdk like in android/ios sdks. How can I do that?

**Comment by dana11235** [comment]
@mrserfr Can you explain exactly what you mean by session events? Do you mean start and end session events?

**Comment by mrserfr** [comment]
@dana11235 Yes, exactly, I mean start session and end session events

**Comment by haoliu-amp** [comment]
@mrserfr Hey, are you talking about this?
https://help.amplitude.com/hc/en-us/articles/115002323627-Tracking-Sessions
