### ISSUE TITLE
Do I need to add exceptions to proguard.pro  ?

### ISSUE THREAD

**Issue by otopba** [amplitude/Amplitude-Flutter#38]
Android manual says that I have to add this lines to proguard.pro:
```
-keep class com.google.android.gms.
-dontwarn okio.**
```

Do I need to add this lines if I use this library?

**Comment by haoliu-amp** [comment]
@otopba Could you point me out where that manual is? Thx

**Comment by haoliu-amp** [comment]
NOW, yes you do if you are going to track advertising Id under obfuscation mode (means you're using proguard).
