### ISSUE TITLE
Log events with properties seems not work?

### ISSUE THREAD

**Issue by blaizechuang** [amplitude/Amplitude-Flutter#40]
Hi,
I tried to send events with properties as the sample code:
analytics.logEvent(name: 'add_friend', properties: { 'key': 'value' });

But I can't see Event Properties field on the amplitude server console
The plugin I used was 1.0.1.

Thanks.

**Comment by nikitattt** [comment]
This way should work:
```
analytics.logEvent(
  name: 'add_friend',
  properties: { 
     'event_properties' : { 
         'key': 'value',
         'key': 'value'
      } 
  }
);
```
