### ISSUE TITLE
AppLifecycleState enum suspending removed

### ISSUE THREAD

**Issue by JohnMusleh** [amplitude/Amplitude-Flutter#42]
according to this PL: https://github.com/flutter/engine/pull/11913 the AppLifecycleState 
enums were changed, suspending was removed.

Needs to be fixed in session.dart:
https://github.com/amplitude/Amplitude-Flutter/blob/master/lib/src/session.dart

The error I get:
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/amplitude_flutter-1.1.0/lib/src/session.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:

**Comment by haoliu-amp** [comment]
It is fixed. Please use 1.1.1. https://pub.dev/packages/amplitude_flutter
