### ISSUE TITLE
Add null safety

### ISSUE THREAD

**Issue by percula** [amplitude/Amplitude-Flutter#42]
## Summary
Flutter now supports null safety in the stable channel. Please migrate this package to null safety. You can use the `dart migrate` tool.

**Comment by incendial** [comment]
Created a PR for null safety support #43

**Comment by yuhao900914** [comment]
We just release the new version which sypport null safety. 
Thanks for your PR request. @incendial

**Comment by incendial** [comment]
@yuhao900914 thanks for the review!
