### ISSUE TITLE
Unable to use permission handler with recent release

### ISSUE THREAD

**Issue by bytepoets-mzi** [amplitude/Amplitude-Flutter#44]
Hi,

#39 introduced a new permission check that assumes none is ever using `registrar.addRequestPermissionsResultListener` except Amplitude. If you use a different flutter plugin to request permissions, Amplitude will crash the application.

The bug here is the assumption, that `mResult` is always set when you use just Amplitude, but can be null with any other permission request: https://github.com/amplitude/Amplitude-Flutter/blob/master/android/src/main/java/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.java#L54

**Comment by BansookNam** [comment]
same here. it's critical bug.

**Comment by haoliu-amp** [comment]
Fixed. New version is out! https://pub.dev/packages/amplitude_flutter

Thanks for helping us improving our SDK!
