### ISSUE TITLE
Regression in app size

### ISSUE THREAD

**Issue by Zazo032** [amplitude/Amplitude-Flutter#47]
In the app I'm working on, I was using this branch: https://github.com/amplitude/Amplitude-Flutter/pull/41. After it got merged/solved, and released as `1.1.1`, the appbundle size went from 24.1mb to 24.7mb. That PR was based on `1.0.1`, so the regression happened between `1.0.1` and `1.1.1`. Is this really a regression in the size of the plugin, or is this size increase intended? Thanks.

**Comment by haoliu-amp** [comment]
Hey,

That branch was developed by an individual developer which was based on our 1.0.1. The most recent release before 1.1.1 is 1.1.0 which added more features (which also means more files).

The change I made to release 1.1.1 is based on 1.1.0. That's why it is slightly bigger.
