### ISSUE TITLE
A user ID that comes from another project is set without calling setUserID

### ISSUE THREAD

**Issue by mgonzalezc** [amplitude/Amplitude-Flutter#47]
## Expected Behavior
The user profile should not show a user ID, only Amplitude ID, as setUserID was not called

## Current Behavior
User profile shows a user ID that comes from another project linked to a different app with a different bundle ID. Both projects are inside the same organization

## Steps to Reproduce
This issue was only reproducible in iOS for me. I installed the apps from TestFlight.
You need to have two applications linked to two different projects within the same organization in Amplitude. 
- Application A 
- Application B

1. Install Application A from TestFlight
2. Call setUserID within application A with ID 12345
3. Install Application B from TestFlight
4. Do NOT call setUserId in Application B
5. Go to Amplitude's console, project linked to Application B: user profile shows ID 12345(the one set in A), but user ID should be empty

If Application A is uninstalled before installing B (between steps 2 and 3), then the issue doesn't happen and everything works fine

## Environment
- SDK Version: 2.2.1
- Flutter Version:  2.0.3
- Device: iPhone SE
- Device OS and Version: iOS 14.4.2

**Comment by yuhao900914** [comment]
Hi @mgonzalezc, thanks for pointing out the issue. 
Unfortunately, I cannot reproduce it on my side. 
But if you have two different projects, the API keys on applications should be different. Even you are on the same device, actions on project A will not trigger any events on project B. 

Looks like you are still using the old SDK, have you tried amplitude_flutter v3.1.0?

**Comment by yuhao900914** [comment]
Closed due to no response.
