### ISSUE TITLE
Error: Getter not found: 'detached'

### ISSUE THREAD

**Issue by ciceropablo** [amplitude/Amplitude-Flutter#48]
The error I get:
../../../.asdf/installs/flutter/1.9.1+hotfix.6-stable/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-1.1.1/lib/src/session.dart:64:30: Error: Getter not found: 'detached'.
      case AppLifecycleState.detached:

**Comment by haoliu-amp** [comment]
Flutter did a breaking change in https://github.com/flutter/engine/pull/11913, which removed `suspending` and added `detached`. And we changed that in 1.1.1. 

To use 1.1.1, you need to update your flutter sdk to the latest version.
