### ISSUE TITLE
The plugin is built using an older version of the Android plugin API

### ISSUE THREAD

**Issue by askarsyzdykov** [amplitude/Amplitude-Flutter#49]
When running with Flutter v1.13.0 we get the warning:

```The plugin `amplitude_flutter` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.```

**Comment by haoliu-amp** [comment]
Good to know. Will take a look. Thx.

**Comment by mixdesign** [comment]
@haoliu-amp Hi there, any progress on this? We need this fix. Thanks

**Comment by haoliu-amp** [comment]
Hello! We'll push out a new release very soon!

**Comment by haoliu-amp** [comment]
Pls check out version 1.1.2. It should resolve this issue. Thanks!
