### ISSUE TITLE
Unable to see event on Amplitude

### ISSUE THREAD

**Issue by fmmalta** [amplitude/Amplitude-Flutter#5]
Hi, I'm using Amplitude on 2.0.0 version and I'm trying to log an event to my dashboard, but unsuccessful, I'd like your help.

``` dart
import 'package:adam/app_config.dart';
import 'package:amplitude_flutter/amplitude.dart';

class AppAnalytics extends Amplitude {
  static final AppAnalytics _analytics = AppAnalytics._internal();

  AppAnalytics._internal() : super('MyCompany');

  factory AppAnalytics() => _analytics;

  static Future<void> start() async {
    await _analytics.init(AppConfig.instance.analyticsKey);
  }

  static void initTrackWithUserId(String userId, {String screenName}) {
    _analytics
      ..setUserId(userId)
      ..trackingSessionEvents(true)
      ..logEvent('acessed_$screenName');
  }

  static void sendEvent(String event, {Map<String, dynamic> props}) {
    _analytics.logEvent(event, eventProperties: props);
  }
}
```

I've built this Singleton class and I'm starting at main.dart calling `start()` above.

I have some previous events that are logging but I'm trying to add new ones but they don't show up at Amplitude for me and I don't know what else to do, besides that, I have some questions.

What is the instanceName? It's the my project's name on Amplitude? My workspace name? Or can it be any name as I wish?

Using as a singleton is doing fine with some old events, but new ones, don't.

Am I missing something? Does the singleton is a good way to keep going?

**Comment by haoliu-amp** [comment]
Would you like to try our SDK without having your own wrapper/inheritance? 
To do it, please follow the example. https://github.com/amplitude/Amplitude-Flutter

instance name is:
Name of the SDK instance (e.g. no name for the default instance or a custom name for a named instance).

**Comment by fmmalta** [comment]
How can I retrieve the instance? Inherited? Instantiating a new one? It only has a function on README.md's example

Should I follow from example folder? Which means that I have to instantiate Amplitude right inside main.dart? 

What's the difference between my code and the example? I know, perhaps the InheritedWidget AppState, that's why I'm asking.

**Comment by haoliu-amp** [comment]
To retrieve the instance, do

```
    final Amplitude analytics = Amplitude.getInstance(instanceName: "project");
```

To initialize, do.
```
    // Initialize SDK
    analytics.init(widget.apiKey);
```

You don't need to call the constructor explicitly.

**Comment by fmmalta** [comment]
So this `analytics` variable should be a global instance?

**Comment by fmmalta** [comment]
``` dart 
class AppAnalytics {
  static Amplitude _analytics = Amplitude.getInstance();

  static Future<void> start() async {
    await _analytics.init(AppConfig.instance.analyticsKey);
  }

  static void initTrackWithUserId(String userId, {String screenName}) {
    _analytics
      ..setUserId(userId)
      ..trackingSessionEvents(true)
      ..logEvent('acessed_$screenName');
  }

  static void sendEvent(String event, {Map<String, dynamic> props}) {
    _analytics.logEvent(event, eventProperties: props);
  }
}
```

This is the new code, no more singletons, still not working, what I'm missing?

Does static functions is a problem? I've added some break points to check if the functions were being called correctly and they were, the key was being passed, the instance is not null... I don't know what else can be done.

**Comment by fmmalta** [comment]
Apparently you can't delete a previous logged event and then submit another one with the exactly previous' name. I had an event called: "tapped_button", had deleted, and tried to submitted again with the same name and nothing was happening, so I've uploaded as: "tapped_button1" and worked fine. Why this? This should be in bold at the docs

**Comment by fmmalta** [comment]
I've figure it out
