### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by Zazo032** [amplitude/Amplitude-Flutter#51]
I got this kind of warning while building my app:

```
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...                       11ms
√ `android\settings_aar.gradle` created successfully.
Building plugin amplitude_flutter...
```

Now that AndroidX support is stable in Flutter, the plugin should be migrated to support it.

**Comment by isacjunior** [comment]
The same problem here.

**Comment by samuelematias** [comment]
The same problem here too.

**Comment by haoliu-amp** [comment]
@Zazo032 , @isacjunior , @samuelematias  Hey! Could someone help answer a few questions to help me investigate?

1. Wonder which command trigger this error? I tried to run `flutter build apk` but not seeing the error.
2. Which version of sdk do you use? 1.1.3?

Thanks!

**Comment by haoliu-amp** [comment]
@Zazo032 @isacjunior @samuelematias 
Could you help give me more details about this? See above pls.

**Comment by Zazo032** [comment]
I think it was during a `flutter build appbundle` or `flutter run --release`, can't remember properly. It only appeared once and never appeared again, if that's useful to you (didn't stop the build/run process). Try running also `flutter clean`, `flutter pub cache repair`, `flutter packages get` and `flutter packages upgrade` prior to build or release to see if it appears, but I can't reproduce it now.

**Comment by Zazo032** [comment]
It did happen again, using version 1.1.3 of the plugin, and using the "Play" button on Android Studio (`flutter run`). Here's my `flutter doctor -v` output just in case it's useful:

```
[√] Flutter (Channel master, v1.13.8-pre.70, on Microsoft Windows [VersiÃ³n 10.0.18363.535], locale es-ES)
    • Flutter version 1.13.8-pre.70 at C:\src\flutter
    • Framework revision db08afd07f (13 hours ago), 2020-01-09 19:28:01 -0800
    • Engine revision f001ea29f1
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
```

**Comment by haoliu-amp** [comment]
@Zazo032 Thank you! I tried with it but I didn't see the error. However, I did migration for all our android libraries to be androidx for amplitude plugin in v1.1.4. Please try it and let me know if the issue is solved. Thanks!

https://pub.dev/packages/amplitude_flutter

**Comment by samuelematias** [comment]
> @Zazo032 @isacjunior @samuelematias
> Could you help give me more details about this? See above pls.

Hey! @haoliu-amp , I'm sorry for the delay.
I'm update for the **v1.1.4** and still have some problems.
So, i need update some android code on my project:

On **gradle-wrapper.properties**, update **THIS** `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

On **build.gradle**, update **THIS** `classpath 'com.android.tools.build:gradle:3.2.1'` to `classpath 'com.android.tools.build:gradle:3.3.1'`

so it worked!

Thank you @haoliu-amp for the support.
CYA!

**Comment by haoliu-amp** [comment]
@samuelematias Ya, sometimes it will require you keep your gradle and some libraries. I'm really glad you figured it out and posted how you did it.

Thank you!
