### ISSUE TITLE
Manually add Phone permission

### ISSUE THREAD

**Issue by Zazo032** [amplitude/Amplitude-Flutter#56]
Currently, if you add this plugin to your app, even though I don't use the Phone permissions, it appears on my app's settings to enable it.

This could be solved by removing this line:
https://github.com/amplitude/Amplitude-Flutter/blob/master/android/src/main/AndroidManifest.xml#L3

And asking the user to add it to the app's manifest if they want to use that permission.

**Comment by haoliu-amp** [comment]
Close this since it will be released soon
