### ISSUE TITLE
Android sessions not being reported the same as iOS sessions.

### ISSUE THREAD

**Issue by brax10ward** [amplitude/Amplitude-Flutter#57]
## Expected Behavior
When I set up the SDK according to the documentation then the start of a user's session should be reported the same for iOS and Android.

## Current Behavior
iOS will report when a session starts/ends but android does not.

## Possible Solution
The only solution I have found is to call `analytics.logEvent()` to get data showing up for android.

## Steps to Reproduce
1. Create a project from the amplitude flutter example [app](https://github.com/amplitude/Amplitude-Flutter/tree/main/example) 
2. In the `my_app.dart` file change the `initState()` to match the getting started guide.
```
  @override
  void initState() {
    super.initState();

    analytics = Amplitude.getInstance();
    analytics.init(widget.apiKey);
    analytics.setUserId("test_user");
    analytics.trackingSessionEvents(true);
  }
```
3. Running this for iOS will send data to the web interface
4. Running this for android will NOT send data to the web interface

## Environment
- SDK Version: v3.2.1
- Flutter v2.2.2
- Device: iPhone 11Pro Simulator, Pixel 2
- Device OS and Version: iOS 14.5, Android 11

**Comment by dantetam** [comment]
@yuhao900914 do you have any insight on this particular issue?

**Comment by yrslvr** [comment]
I have the same problem. Is it going to be fixed?

**Comment by haoliu-amp** [comment]
Hello, we will take a look. Thanks for reporting.

**Comment by vishna** [comment]
I can repo this as well - as a consequence `getSessionId` has different behaviour on iOS/Andoid

on iOS it's different after 5 minutes (default session length)
on Android it's usually stuck (even if firing extra event/session expired)

**Comment by vishna** [comment]
...unsure if my PR fixes the mentioned issue 😓  ...but it for sure triggers session start/end events more frequently (just like on iOS side)

**Comment by yuhao900914** [comment]
On native Android, currently, sessionTimeout period has different values for using and not using foreground tracking. If the not using foreground tracking, the sessionTimeout period is 30 mins instead of 5 mins.  
This PR will fix Android and iOS session event unalignment. Please check the latest version v3.8.1. 
Thanks, @vishna.
