### ISSUE TITLE
Missing Advertisement Id (ADID/IDFA) for user

### ISSUE THREAD

**Issue by Harits514** [amplitude/Amplitude-Flutter#57]
There is a problem in our Amplitude integration with Adjust. For some reason just a few of our users are have any [adjust] event in their event stream(i.e. the attribution event [adjust] Install or some [adjust] custom event), while nearly all of our users should actually have some [adjust] event in their event streams.

After some research we found that the user that successfully get [adjust] event is our old users that has used our native android/ios app(before we moved to flutter) that has android/ios amplitude sdk in it. When you see the raw data for the [adjust] event, the listed device_id is somehow different from the device_id of the event that sended from the flutter app, but is the same with the last event that sended from our native app, which means that the [adjust] event device id refers to the device id that the user has when they is still using the native app.

Since from the docs that i read it was mentioned that Amplitude match the event from Adjust to know which user do the event is by using the sended Advertisement Id(ADID/IDFA), i think the Amplitude flutter sdk is not sending the user advertisment id to Amplitude.

It was further proofed when i try to use the Amplitude attribution API. If i fill the ADID params with adid of a device that has installed our native app in the past, the attribution API will work, but, if i fill it with adid of a device that never has installed our native app before, and has the flutter app in it, the attribution API will not work, even though that user activity already recorded in amplitude and it already past 72 hours(the time when the attribution call will be dropped if there is no matching user).

We are currently using version 1.1.4, and this problem make us lost a lots of attribution data, can you please help me with this issue?

**Comment by haoliu-amp** [comment]
Our Flutter SDK doesn't track advertising id at this moment. We will add support to it.

**Comment by haoliu-amp** [comment]
1.2.0 is released. Please use this to track advertising id. I also added documentation for it in README.
https://pub.dev/packages/amplitude_flutter

Thanks.
