### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by Abhishek01039** [amplitude/Amplitude-Flutter#59]
## Summary

Is Amplitude-Flutter free?

If not then is there any free tier term?

**Comment by ajhorst** [comment]
Hi @Abhishek01039, all Amplitude SDKs themselves are free to use. We have a free tier for the Amplitude product itself, for users with fewer than 10 million events per month. You can see more about Amplitude plans here https://amplitude.com/pricing

**Comment by yuhao900914** [comment]
@Abhishek01039  Here is the setup information. https://developers.amplitude.com/docs/flutter-setup

**Comment by Abhishek01039** [comment]
Sure 
Thanks
