### ISSUE TITLE
App crashing on calling setUserProperties

### ISSUE THREAD

**Issue by fmmalta** [amplitude/Amplitude-Flutter#6]
It's me again, I'm trying to calling setUserProperties but the app, at least on simulator, keep crashing. 

``` dart
class AnalyticsRepositoryImpl implements AnalyticsRepository {
  final Amplitude analytic = Amplitude.getInstance(instanceName: 'Vitta');

  @override
  Future<void> setUserProps(Map<String, dynamic> props) async {
    await analytic.setUserProperties(props);
  }
}
```

I'm missing something? Again?

**Comment by haoliu-amp** [comment]
Hello, could you provide crash report? stracktraces?

**Comment by Sublustris** [comment]
it crashing only on iOS. The only error message is:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

code is the same:
```
var amp = Amplitude.getInstance(instanceName: ampapikey);
amp.init(ampapikey);
amp.setUserId("usr-q5rag46jkfnbey78mjjh1gfd");
amp.trackingSessionEvents(true);

Map<String, dynamic> userParams = {
      "date": "01.06.2020",
      "name": "Andrew",
      "buildNumber": "0.2.0.70",
    }; 
amp.setUserProperties(userParams);
```

without "amp.setUserProperties(userParams);"  it works fine on both platforms.

**Comment by fmmalta** [comment]
Can't provide an error log or strackTrace, my emulator just crash without giving me nothing, even on terminal. Same as @Sublustris said, without ```setUserProperties(params)``` works just fine on both platforms

**Comment by Sublustris** [comment]
> Can't provide an error log or strackTrace, my emulator just crash without giving me nothing, even on terminal. Same as @Sublustris said, without `setUserProperties(params)` works just fine on both platforms

Same thing. It crashes suddenly and debugger instantly loses connection with the application.

**Comment by fmmalta** [comment]
I've also tried to change to ```Map<dynamic, dynamic>``` it didn't work also.

**Comment by haoliu-amp** [comment]
Thank you! We will look into it.

**Comment by haoliu-amp** [comment]
Pls try v2.1.0. Should have this fixed.
https://pub.dev/packages/amplitude_flutter
