### ISSUE TITLE
java.lang.NoSuchMethodError: No static method userAgent ()

### ISSUE THREAD

**Issue by kva97** [amplitude/Amplitude-Flutter#64]
## Current Behavior
The error occurs:
java.lang. NoSuchMethodError: Nostaticmethod user Agent()Ljava/Lang/String; in classLokhttp3
Occurs at the initialization stage of the plugin, when the init() method is called, after that the application crashes.

## Possible Solution

It is the result of incompatibility of the versions of okhttp3 in different plugins/ libraries of the project, since many other libraries use the version of the okhttp API 3.12.+.
To solve the problem, you need to build from the build file.gradle should remove an explicit reference to the version of okhttp3 4.2.2, since these different versions of the okhttp3 API are not compatible in the same project.

## Environment
- SDK Version: 
- Flutter Version: 
- Device: 
- Device OS and Version:

**Comment by yuhao900914** [comment]
We think that's the okhttp issue, we are going to remove the okhttp. Will close this ticket for now. Thanks. @kva97
