### ISSUE TITLE
Multiple Amplitude instances in one app 

### ISSUE THREAD

**Issue by jfushada** [amplitude/Amplitude-Flutter#69]
Hello, I was wondering if it was possible to instantiate multiple Amplitude projects in one Flutter app?

**Comment by haoliu-amp** [comment]
I think you might be able to achieve it if you customize the `ServiceProvider` when creating AmplitudeFlutter instance.
This is the constructor you wanna use. 
```
  AmplitudeFlutter.private(this.provider, this.config) {
    _init();
  }
```

@reinaldomoreira just did a change for this.

Although I agree this is not the best way and we will revisit this later.

**Comment by jfushada** [comment]
Hello,

I managed to instantiate multiple Amplitude projects by customizing `Client` (specifically by removing ` if (_instance != null) { return _instance; }`), as well as separating the session and db instances.   

Thank you very much for your help!

**Comment by reinaldomoreira** [comment]
I would say that you will be better off creating your own client and overriding what you need to do instead of removing the specs of Singleton of AmplitudeFlutter Client.

**Comment by jfushada** [comment]
@reinaldomoreira ah I should've been clearer, sorry! I did create my own client, and the main change I did was remove the line of code above in my implementation.
