### ISSUE TITLE
cannot download sdk due to SSL certificate error

### ISSUE THREAD

**Issue by xfumihiro** [amplitude/Amplitude-Flutter#7]
error on running pod install
```
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/f/4/d/Amplitude/5.0.0/Amplitude.podspec.json Response: SSL peer certificate or SSH remote key was not OK, retries: 4
```

should related to May 30 incident  https://status.amplitude.com/

**Comment by haoliu-amp** [comment]
Not sure this is related to Amplitude, but it could be related with `AddTrust External CA Root certificate` issue globally. Now it I think it should work properly.
