### ISSUE TITLE
Android error during build / iOS work: Execution failed for task ':amplitude_flutter:compileDebugKotlin'.

### ISSUE THREAD

**Issue by yelkamel** [amplitude/Amplitude-Flutter#73]
Hello

I want to remove Segment to use directly amplitude for track event analytics.
So I follow step by step the guideline to add amplitude-flutter 

on iOS it's work but on Android I have this error during the build:

`'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (196, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[   +6 ms] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (200, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (202, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (209, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (215, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (218, 24): Class
'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
[        ] The class is loaded from /Users/yelkamel/.gradle/caches/transforms-2/files-2.1/69cffba187c9174af5a287de98f1cddd/jetified-kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (226, 27): For-loop
range must have an 'iterator()' method
[        ] e: /Users/yelkamel/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.5.0/android/src/main/kotlin/com/amplitude/amplitude_flutter/AmplitudeFlutterPlugin.kt: (228, 25): For-loop
range must have an 'iterator()' method
[ +145 ms] > Task :amplitude_flutter:compileDebugKotlin FAILED
[  +96 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':amplitude_flutter:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 9 actionable tasks: 1 executed, 8 up-to-date
[ +613 ms] Running Gradle task 'assembleDebug'... (completed in 11.4s)
[+2930 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +10 ms] "flutter run" took 19,348ms.
[  +14 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
`

## Environment
- SDK Version: ">=2.7.0 <3.18.1"
- Flutter Version: 2.5
- Device OS and Version: Android 10

**Comment by yuhao900914** [comment]
@yelkamel  we recently update our kotlin-gradle-plugin to 1.5.30. Feels like the error might related with that updates. 
What's your kotlin version in your project?

**Comment by Nico04** [comment]
In my case, setting these values resolved the issue :
```
ext.kotlin_version = '1.5.31'
classpath 'com.android.tools.build:gradle:7.0.3'
gradle-7.0.2-all.zip
multiDexEnabled true
```

Note : I have another issue now, trying to figure it out

**Comment by yuhao900914** [comment]
You can also check our example app as a reference.  
https://github.com/amplitude/Amplitude-Flutter/blob/main/example/android/build.gradle

This pr includes the example changes when upgrading the kotlin version to 1.5.30. 
https://github.com/amplitude/Amplitude-Flutter/pull/68/files

**Comment by GlebUstimenkoWMG** [comment]
I see the same issue

**Comment by yuhao900914** [comment]
Can you guys provide an example app? Then I can try to figure out what's the issue is.

**Comment by dutsky** [comment]
To reproduce this bug:
1) create new flutter app: `flutter create testapp`
2) add `amplitude_flutter: ^3.2.1` to `pubspec.yaml` (stanza from [your official documentation](https://developers.amplitude.com/docs/flutter-setup))
3) run it

**Comment by yuhao900914** [comment]
https://github.com/yuhao900914/flutter_test_app
Here is the flutter example app. It works all fine on android Gradle build and on [flutter release build](https://flutter.dev/docs/deployment/android#building-the-app-for-release) on both APK and app bundle. 
<img width="671" alt="Screen Shot 2021-10-27 at 1 29 14 PM" src="https://user-images.githubusercontent.com/13028329/139142303-e86df589-15fb-4c60-87cf-f3d6bab10a7b.png">

After you init the test app and install the amplitude_flutter you need to change the kotlin_version version to 1.5.0 like here, then all works fine. https://github.com/yuhao900914/flutter_test_app/blob/main/android/build.gradle#L2

**Comment by dutsky** [comment]
It is okay to update your kotlin version if you are just starting a new app, but it is not good when your project stops building because amplitude's minor update requires you to update kotlin version for the entire project.
And it seems you need to update your documentation then, because project will not build until you change your kotlin_version(and documentation didn't say anything about it).
Thanks!

**Comment by yuhao900914** [comment]
@dutsky  Just release v3.7.0, which downgrade the kotlin gradle plugin version to 1.3.40 to fix amplitude_flutter incompatible to project with kotlin gradle plugin version < 1.4.0.
Please try it out and let me know if that's still not working.

**Comment by dutsky** [comment]
Thank you, @yuhao900914! It works! :3

**Comment by idrisadetunmbi** [comment]
This seems to have changed in v3.9.0. It no longer builds on this version with the subject error.
