### ISSUE TITLE
PlatformException(error, TypeError: Cannot read properties of undefined (reading 'getInstance'), null, null)

### ISSUE THREAD

**Issue by JideGuru** [amplitude/Amplitude-Flutter#89]
## Expected Behavior
Amplitude should get initialized on Web

## Current Behavior
I get an error instead when I run the code on the web but it works on mobile
`PlatformException(error, TypeError: Cannot read properties of undefined (reading 'getInstance'), null, null)`

## Steps to Reproduce
 

1. Add amplitude ^3.8.0 to flutter project
2. Try initializing amplitude with the following code

```
Amplitude amplitude = Amplitude.getInstance();
amplitude.init(Config.amplitudeAppId);
```
3.  
4.

## Environment
- SDK Version: ^3.8.0
- Flutter Version: 2.5.1
- Device: Chrome
- Device OS and Version: Web, Chrome Version 96.0.4664.55 on Mac

**Comment by nanox77** [comment]
I have the same problem in Flutter Web 2.5.3

**Comment by yuhao900914** [comment]
Did you append the Amplitude-Javascript snippet in to your index.html? @JideGuru 
https://developers.amplitude.com/docs/flutter-setup#flutter-web-support

**Comment by JideGuru** [comment]
My bad. I've added the javascript snippet and now it's working

**Comment by mhkojoana** [comment]
how did you add the javascript snippet?? i'm currently experiencing that problem

**Comment by Spixz** [comment]
Hello, I have the same error even with the good import [according to the flutter documentation](https://www.docs.developers.amplitude.com/data/sdks/flutter/#initialization). My app run in the web browser.
```
import 'package:amplitude_flutter/amplitude.dart';
import 'package:amplitude_flutter/identify.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Amplitude.getInstance().init("my_key");

  runApp(const MyApp());
}
```
OR
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final Amplitude analytics = Amplitude.getInstance(instanceName: "project");

    analytics.init("my_key");

    analytics.logEvent('MyApp startup', eventProperties: {
      'friend_num': 10,
      'is_heavy_user': true
    });

  runApp(const MyApp());
}
```

Thanks for your help.

Amplitude_flutter: ^3.13.0
Flutter Version: 3.3.9
Device: Chrome
Device OS and Version: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
