### ISSUE TITLE
Is it necessary to add com.google.android.gms:play-services-ads to my app?

### ISSUE THREAD

**Issue by otopba** [amplitude/Amplitude-Flutter#9]
Hello!
Is it necessary to add `com.google.android.gms:play-services-ads` to my android app? 
This page says yes https://developers.amplitude.com/docs/ios-ios-advertising-id-idfa but example in this repo has no play-services-ads. Who is right?

**Comment by haoliu-amp** [comment]
@otopba If you wanna track advertising Id, then you would need to add it.
https://help.amplitude.com/hc/en-us/articles/115003135607-Tracking-Unique-Users

If you don't use advertising id, then you don't have to.

**Comment by otopba** [comment]
@haoliu-amp Thank you. Maybe you should mark the second step as optional?
![image](https://user-images.githubusercontent.com/4225279/83551788-80135880-a511-11ea-8a23-130d69c012a4.png)

https://developers.amplitude.com/docs/flutter-setup

**Comment by haoliu-amp** [comment]
@otopba Thank you, just added.

**Comment by otopba** [comment]
@haoliu-amp Thank you. So fast =)
